### PR TITLE
Fix bug where findGitRepo always returns null

### PR DESCRIPTION
**Pull request by iamchetan**
The Query annnotation has incorrect parameter (options.repoUrl) due to which findGitRepo method always returns null.
The correct parameter is options.url as seen in the value of com.capitalone.dashboard.model.GitRepo class' REPO_URL constant.

**Affects:** \<bitbucket-collector-version-number>.

* [Individual Agreement](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform)
* [Corporate Agreement](https://docs.google.com/forms/d/e/1FAIpQLSeAbobIPLCVZD_ccgtMWBDAcN68oqbAJBQyDTSAQ1AkYuCp_g/viewform?usp=send_form)

- [x] I Have signed the CLA

---

### CODE REVIEW

**Comment by rvema** [comment]
@iamchetan I didnt not find unit tests for this change, can you confirm if this has been tested if so can up date the PR detail with the version where this change has been tested against

**Comment by rvema** [comment]
@iamchetan can you provide the evidence of testing so that this change can be accepted

**Review by rvema — APPROVED** [review]
lgtm

**Comment by rvema** [comment]
@shishirchaturvedi I would appreciate if you can take a look at this change and provide your thoughts.

**Comment by shishirchaturvedi** [comment]
@rvema This change LGTM. The url parameter is correct as it can be verified from com.capitalone.dashboard.model.GitRepo. 
However, this method is not used in this repository(at least I didn't find its usage) - com.capitalone.dashboard.repository.GitRepoRepository#findGitRepo.

**Comment by rvema** [comment]
Thanks for your help

**Pull request merged**
